#!/bin/bash

pkill picom

# setup lockscreen if $LOCK_SCREEN_DISABLE is *not* set
xset s off -dpms
if [[ -z "$LOCK_SCREEN_DISABLE" ]]; then
  xss-lock lock &
  xset +dpms dpms 600 600 600
fi

xset r rate 200 30      # (repeat delay for keys, 200ms to wait before repeat, 30ms rate when holding down key)
setxkbmap us altgr-intl # easier typing of umlauts
[[ -f "$HOME/.Xmodmap" ]] && xmodmap "$HOME/.Xmodmap"

xrdb -DPYWAL_="<${XDG_CACHE_HOME:-$HOME/.cache}/wal/colors.Xresources>" -merge "$HOME"/.xresources
if [[ -d "$HOME/.xrdb.d" ]]; then
  for file in "$HOME"/.xrdb.d/*; do xrdb -merge "$file"; done
fi

dunst &             # notification manager
picom -b &          # compositor
lxpolkit &          # authentication agent
parcellite -n &     # clipboard manager
unclutter -idle 2 & # hide cursor when inactive for 2 seconds
~/.fehbg            # sets wallpaper
