name: Build

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Linux
        run: |
          sudo apt-get update
          sudo apt-get -y upgrade
          sudo apt-get install -y \
            build-essential \
            libx11-dev \
            libxinerama-dev \
            libxft-dev \
            libxcb-res0-dev \
            libxcb-xkb-dev \
            libx11-xcb-dev
          sudo make
